Byeonghyun/naver login create
Fan-Tion/Front-End pull request #66
Opened 2024-07-28 15:08 UTC by Min-byeonghyun

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [x ] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

<br/>

## 반영 브랜치
ex) byeonghyun/naver-login-create -> test

<br/>

## 👨🔧 변경사항

- **AS-IS**
  유저가 네이버로 로그인 할 수 있게 해야됩니다.
  메인 로고가 필요합니다 메인로고 클릭시 홈으로 이동
- **TO-BE**
<br />
 유저가 네이버로 로그인 할 수 있게 백엔드 api 와 연동해서 네이버 로그인 완료
 로고이미지를 만들고 로고클릭시 홈으로 갈 수 있게 해놓았습니다.
## 🎨 이미지 첨부

<img src="파일주소" width="50%" height="50%"/>
메인 로고
![mainLogo2](https://github.com/user-attachments/assets/c7ac8c22-df4c-47b9-9ced-103adc01d18f)

## 👨💻 테스트
 
- [x ] 테스트 코드
- [ x] API 테스트
<br/>

## ➕ 이슈 링크

- [레포 이름 #이슈번호](이슈 주소)

2024-07-28 16:46 UTC, Hira-Yuki requested changes
엑박 문제 해결 후 다시 요청해 주세요.

2024-07-28 16:46 UTC, Hira-Yuki commented on src/components/FindPasswordComponent/index.tsx
> +        <Styled.LogoImage src="/img/mainLogo2.png" />
로컬에선 정상적으로 표시되겠지만 배포하면 엑스박스로 표기될거에요.

2024-07-28 16:46 UTC, Hira-Yuki commented on src/components/NaverComponent/LinkNaverAccount.tsx
> +      <Styled.NaverImg src="/img/naver_login.png" />
여기도 로컬에선 정상적으로 표시되겠지만 배포하면 엑스박스로 표기될거에요.

2024-07-28 16:46 UTC, Hira-Yuki commented on src/components/NaverComponent/NaverLoginButton.tsx
> +      <Styled.NaverImg src="/img/naver_login.png" />
+ 추가 엑박

2024-07-28 16:46 UTC, Hira-Yuki commented on src/components/NaverComponent/UnlinkNaverAccount.tsx
> +      <Styled.NaverImg src="/img/naver_login.png"  />
+ 엑박 추가

2024-07-28 16:46 UTC, Hira-Yuki commented on src/components/SignInComponent/index.tsx
> +        <Styled.LogoImage src='/img/mainLogo2.png'/>
+ 엑박 추가

2024-07-28 16:46 UTC, Hira-Yuki commented on src/components/SignUpComponent/index.tsx
> +        <Styled.LogoImage src="/img/mainLogo2.png" />
+ 여기도 엑박이에요

2024-07-28 16:46 UTC, Hira-Yuki commented on src/layout/LayoutHeader.tsx
> +          <LogoImage src="/img/mainLogo.png" />
+ 엑박

2024-07-28 16:46 UTC, Hira-Yuki commented on src/routes/Routes.tsx
> +        <Suspense fallback={<Loader />}>
fallback을 LoadingScreen으로 처리해 주세요.

2024-07-29 08:41 UTC, Min-byeonghyun commented on src/routes/Routes.tsx
> +        <Suspense fallback={<Loader />}>
이거는 처리했습니다

2024-07-29 11:33 UTC, Hira-Yuki approved these changes

2024-07-29 12:05 UTC, DoHyeongKwonn approved these changes
고생하셨습니다

2024-07-29 13:47 UTC, merged